services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env